### ISSUE TITLE
Falsa broken on python 3.9

### ISSUE THREAD

**Issue by samster25** [mrpowers-io/falsa#22]
Installed the latest main of falsa with python3.9 and get the following error. I believe this can be fixed with
`from __future__ import annotations` to backport support of the annotations.

I also believe `ruff` already has a lint rule for this!

```
(.venv) ➜  Daft git:(main) falsa --help     

Traceback (most recent call last):
  File "/Users/sammy/code/Daft/.venv/bin/falsa", line 5, in <module>
    from falsa.app import entry_point
  File "/Users/sammy/code/Daft/.venv/lib/python3.9/site-packages/falsa/app.py", line 14, in <module>
    from falsa.local_fs import (
  File "/Users/sammy/code/Daft/.venv/lib/python3.9/site-packages/falsa/local_fs.py", line 27, in <module>
    class GroupByGenerator:
  File "/Users/sammy/code/Daft/.venv/lib/python3.9/site-packages/falsa/local_fs.py", line 35, in GroupByGenerator
    self, size: H2ODatasetSizes | int, k: int, nas: int = 0, seed: int = 42, batch_size: int = 5_000_000
TypeError: unsupported operand type(s) for |: 'EnumMeta' and 'type'
```

**Comment by SemyonSinchenko** [comment]
Fixed in the latest release.
